version: 2.1
orbs:
  barkendeploy: navikt/barkendeploy@dev:master
jobs:
  build_jar:
    docker:
      - image: "circleci/openjdk:11-jdk"
    steps:
      - checkout
      - setup_remote_docker
      - barkendeploy/init:
          version_format: ${CIRCLE_SHA1}
      - barkendeploy/gradle-cache-restore
#      - run:
#          name: Run tests
#          command: ./gradlew test
      - run:
          name: Build jar file
          command: ./gradlew shadowJar -x test
      - barkendeploy/gradle-cache-persist
      - barkendeploy/docker-build
      - barkendeploy/docker-login
      - barkendeploy/docker-push

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_jar:
          context: barkendeploy
          filters:
            branches:
              only: master
      - barkendeploy/deploy-publish:
          cluster: dev-fss
          context: barkendeploy
          requires:
            - build_jar
          filters:
            branches:
              only: master
