version: 2.1
orbs:
  barkendeploy: navikt/barkendeploy@dev:master
jobs:
  build_jar:
    docker:
      - image: "circleci/openjdk:11-jdk"
    steps:
      - checkout
      - setup_remote_docker
      - barkendeploy/init
      - barkendeploy/gradle-cache-restore
      - run:
          name: Run tests
          command: ./gradlew test
      - run:
          name: Build jar file
          command: ./gradlew shadowJar -x test
      - barkendeploy/gradle-cache-persist
      - run:
          name: Build and publish Docker image
          command: docker build -t docker.pkg.github.com/navikt/${CIRCLE_PROJECT_REPONAME}:${IMAGE_VERSION} .
  create_deployment:
    docker:
      - image: "navikt/deployment-cli:v0.1.8"
    steps:
      - barkendeploy/workspace-restore
      - barkendeploy/deploy-create:
          cluster: dev-fss
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_jar:
          filters:
            branches:
              only: master
      - create_deployment:
          requires:
            - build_jar
          filters:
            branches:
              only: master
